CREATE DATABASE IF NOT EXISTS tarefa_db;
USE tarefa_db;

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT FALSE
);

SELECT * FROM tasks;